### PR TITLE
added theme and font rules

### PR DESCRIPTION
**Pull request by ajstrand**
Add rules for themes and  fonts in the style of a reply guy. 

This should resolve issue #2.

Let me know if you'd like any changes/adjustments made.

### CODE REVIEW

**Comment by ajstrand** [comment]
my bad, I forgot to actually add the rules to the `index.js` 🤦 let me push up a fix for that really quick.

**Comment by darrenvong** [comment]
Don't forget to prefix all your messages with `ACK-tually` otherwise it's not reply guy bitter enough 😂

**Comment by ajstrand** [comment]
Good point @darrenvong 😆

**Comment by ajstrand** [comment]
@jlengstorf, thanks for letting me contribute!

**Pull request merged**
