### PR TITLE
feat: use and don't use jsx

### PR DESCRIPTION
**Pull request by judicaelandria**
If you found something I did wrong, tell me, please? that would be appreciated :) thanks

### CODE REVIEW

**Comment by threehams** [comment]
Well ACK-tually, you could fix this rule without another one complaining at you. Maybe include the inverse "never use .jsx because it's unnecessary" rule?

**Comment by judicaelandria** [comment]
done, what do you think ?

**Comment by jlengstorf** [comment]
@judicaelandria this is great! would you mind putting in _both_ rules for this? it should yell at you for using JSX _and_ for not using JSX 😂

**Comment by judicaelandria** [comment]
@jlengstorf something like that?

**Comment by jlengstorf** [comment]
lol perfect. thanks!

**Comment by judicaelandria** [comment]
My pleasure :)

**Pull request merged**
